/* Nova 2.0.0 - gran actualización: Study, Workspaces, lectura, rendimiento, accesibilidad, seguridad y experiencia renovada. */
(() => {
  const N = NOVA, { PG } = N;
  const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast2 = m => { try { toast(m); } catch {} };
  const clone = o => { try { return JSON.parse(JSON.stringify(o)); } catch { return {}; } };
  const safeUrl = u => { try { const x = new URL(String(u || '')); return /^https?:$/.test(x.protocol) ? x.href : ''; } catch { return ''; } };
  const currentUrl = () => { try { const t=N.activeWebTab?.()||cur; return safeUrl(t?.wv?.getURL?.()); } catch { return ''; } };
  const currentTitle = () => { try { const t=N.activeWebTab?.()||cur; return t?.el?.querySelector('span')?.textContent || currentUrl() || 'Pestaña'; } catch { return 'Pestaña'; } };

  S.v200 = Object.assign({
    workspaces: [], activeWorkspace: 'general',
    studyProvider: 'nova',
    reader: false,
    a11y: { reduceMotion: false, highContrast: false, uiScale: 100 },
    perfPlus: false
  }, S.v200 || {});
  S.v200.a11y = Object.assign({ reduceMotion: false, highContrast: false, uiScale: 100 }, S.v200.a11y || {});
  if (!Array.isArray(S.v200.workspaces) || !S.v200.workspaces.length) S.v200.workspaces = [{ id:'general', name:'General', icon:'⌂', color:'#8b5cf6', tabs:[] }];
  if (!S.v200.workspaces.some(w => w.id === S.v200.activeWorkspace)) S.v200.activeWorkspace = S.v200.workspaces[0].id;
  save();

  const st = document.createElement('style'); st.id = 'nova20-style'; st.textContent = `
    #nova20-wsbtn,#nova20-studybtn{height:28px;padding:0 10px;border:1px solid var(--bd);border-radius:999px;background:var(--bar);color:var(--fg);cursor:pointer;-webkit-app-region:no-drag;white-space:nowrap}
    #nova20-wsbtn:hover,#nova20-studybtn:hover{border-color:var(--acc);color:var(--acc)}
    #nova20-pop{position:fixed;top:38px;left:120px;z-index:100;display:none;min-width:280px;padding:10px;background:var(--bar);border:1px solid var(--bd);border-radius:calc(var(--r)*1.2);box-shadow:0 20px 70px #000c}
    #nova20-pop.on{display:flex;flex-direction:column;gap:5px}.nova20-wi{display:flex;gap:8px;align-items:center;padding:8px;border:0;background:transparent;color:var(--fg);border-radius:var(--r);cursor:pointer;text-align:left}.nova20-wi:hover{background:color-mix(in srgb,var(--acc) 12%,transparent)}
    .nova20-card{padding:14px;border:1px solid var(--bd);background:var(--bar);border-radius:calc(var(--r)*1.25);display:flex;flex-direction:column;gap:9px}.nova20-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:10px}.nova20-chip{padding:10px;border:1px solid var(--bd);border-radius:var(--r);background:color-mix(in srgb,var(--bar) 82%,transparent)}
    #nova20-study{position:absolute;inset:0;z-index:60;background:var(--bg);display:none;flex-direction:column}.nova20-studybar{display:flex;align-items:center;gap:7px;padding:7px;background:var(--bar);border-bottom:1px solid var(--bd);flex-wrap:wrap}.nova20-studybar b{margin-right:auto;color:var(--acc)}.nova20-study-split{flex:1;display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);min-height:0}.nova20-study-pane{min-width:0;min-height:0;position:relative;background:#fff}.nova20-study-pane+ .nova20-study-pane{border-left:1px solid var(--bd)}.nova20-study-pane webview{display:flex!important;position:absolute!important;inset:0!important;width:100%!important;height:100%!important}.nova20-study-ai{position:absolute;inset:0;display:flex;flex-direction:column;background:var(--bar)}.nova20-study-head{padding:12px;border-bottom:1px solid var(--bd)}.nova20-study-chat{flex:1;overflow:auto;padding:12px;display:flex;flex-direction:column;gap:8px}.nova20-study-msg{max-width:90%;padding:9px 11px;border-radius:var(--r);white-space:pre-wrap}.nova20-study-msg.u{align-self:flex-end;background:var(--acc);color:#fff}.nova20-study-msg.a{background:var(--bg);border:1px solid var(--bd)}.nova20-study-compose{display:flex;gap:7px;padding:8px;border-top:1px solid var(--bd)}
    .nova20-welcome{display:flex;flex-direction:column;gap:13px}.nova20-hero{width:100%;max-height:330px;object-fit:cover;border-radius:calc(var(--r)*1.4);border:1px solid var(--bd)}.nova20-feature{min-height:120px}.nova20-feature h3{margin:0;color:var(--acc)}
    .nova20-news{display:flex;flex-direction:column;gap:12px}.nova20-release{padding:16px;border:1px solid var(--acc);border-radius:calc(var(--r)*1.3);background:linear-gradient(135deg,color-mix(in srgb,var(--acc) 18%,var(--bar)),var(--bar));display:flex;flex-direction:column;gap:8px}.nova20-list{margin:0;padding-left:20px;display:flex;flex-direction:column;gap:5px}
    .nova20-reader-active{box-shadow:inset 0 0 0 3px color-mix(in srgb,var(--acc) 25%,transparent)}
    body.nova20-highcontrast{filter:contrast(1.12) saturate(1.08)}body.nova20-scale90{font-size:90%}body.nova20-scale110{font-size:110%}body.nova20-scale125{font-size:125%}body.nova20-reduced *{animation:none!important;transition:none!important;scroll-behavior:auto!important}
    @media(max-width:900px){.nova20-study-split{grid-template-columns:1fr}.nova20-study-pane:last-child{display:none}.nova20-study-split.nova20-show-ai .nova20-study-pane:last-child{display:block;position:absolute;inset:0}.nova20-study-split.nova20-show-ai .nova20-study-pane:first-child{display:none}}
  `; document.head.appendChild(st);

  /* ---------- Workspaces ---------- */
  const ws = () => S.v200.workspaces.find(w => w.id === S.v200.activeWorkspace) || S.v200.workspaces[0];
  const captureWorkspace = () => { const w = ws(); if (!w) return; w.tabs = tabs.map(t => { try { const u = safeUrl(t.wv.getURL()); if (!u || isNT(u) || t.wv.classList.contains('ipage')) return null; return { u, title:t.el.querySelector('span')?.textContent||'', g:t.g||null, p:t.el.classList.contains('pin') }; } catch { return null; } }).filter(Boolean).slice(0,40); save(); };
  const destroyTabs = () => { tabs.slice().forEach(t => { try { t.wv.remove(); } catch {} try { t.el.remove(); } catch {} }); tabs.length = 0; cur = null; $('#tabs').replaceChildren(); };
  const loadWorkspace = () => { const w = ws(); if (!w) return; const items = Array.isArray(w.tabs) ? w.tabs.slice(0,40) : []; if (!items.length) { newTab(); return; } items.forEach(x => { const t = newTab(x.u); if (x.g && S.groups[x.g]) t.g = x.g; if (x.p) t.el.classList.add('pin'); }); typeof NOVA.renderGroups === 'function' && NOVA.renderGroups(); };
  const switchWorkspace = id => { if (id === S.v200.activeWorkspace) return; captureWorkspace(); const target = S.v200.workspaces.find(x => x.id === id); if (!target) return; S.v200.activeWorkspace = id; save(); destroyTabs(); loadWorkspace(); refreshWorkspaceUI(); toast2('Espacio: ' + target.name); };
  const refreshWorkspaceUI = () => { const b = $('#nova20-wsbtn'); if (b) b.textContent = '▦ ' + ws().name; const pop = $('#nova20-pop'); if (pop) { pop.innerHTML = `<div class="mut" style="padding:4px 8px">Espacios de trabajo</div>${S.v200.workspaces.map(w=>`<button class="nova20-wi" data-w="${esc(w.id)}"><span style="width:24px;text-align:center">${esc(w.icon||'•')}</span><span style="flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis">${esc(w.name)}</span>${w.id===S.v200.activeWorkspace?'<b style="color:var(--acc)">Activo</b>':''}</button>`).join('')}<hr style="border:0;border-top:1px solid var(--bd);width:100%;margin:3px 0"><button class="nova20-wi" id="nova20-newws">＋ Nuevo espacio</button><button class="nova20-wi" id="nova20-managews">⚙ Administrar espacios</button>`; pop.querySelectorAll('[data-w]').forEach(x=>x.onclick=()=>{pop.classList.remove('on');switchWorkspace(x.dataset.w)}); pop.querySelector('#nova20-newws')?.addEventListener('click',createWorkspace); pop.querySelector('#nova20-managews')?.addEventListener('click',()=>{pop.classList.remove('on');newTab('nova://workspaces')}); } };
  const createWorkspace = async () => { const r = await N.dlg?.('Nuevo espacio',[{label:'Nombre',value:'Nuevo espacio'},{label:'Icono',value:'◈'}],'Crear'); if (!r) return; const id='ws-'+Date.now().toString(36); captureWorkspace(); const n={id,name:String(r[0]||'Nuevo espacio').slice(0,40),icon:String(r[1]||'◈').slice(0,2),color:'var(--acc)',tabs:[]}; S.v200.workspaces.push(n); save(); switchWorkspace(id); };
  const renameWorkspace = async id => { const w=S.v200.workspaces.find(x=>x.id===id); if(!w)return; const r=await N.dlg?.('Editar espacio',[{label:'Nombre',value:w.name},{label:'Icono',value:w.icon||'◈'}],'Guardar'); if(!r)return; w.name=String(r[0]||w.name).slice(0,40);w.icon=String(r[1]||w.icon).slice(0,2);save();refreshWorkspaceUI(); };
  const deleteWorkspace = id => { if(S.v200.workspaces.length<=1)return toast2('Debe quedar al menos un espacio.'); if(id===S.v200.activeWorkspace)return toast2('Cambia de espacio antes de eliminarlo.'); const w=S.v200.workspaces.find(x=>x.id===id); if(!w)return; if(!confirm('¿Eliminar el espacio «'+w.name+'»?'))return; S.v200.workspaces=S.v200.workspaces.filter(x=>x.id!==id);save();refreshWorkspaceUI(); };
  const renderWorkspacesPage = r => { const render=()=>{ r.innerHTML=`<h2>Espacios de trabajo</h2><span class="mut">Organiza grupos de pestañas por contexto. Cada espacio recuerda sus pestañas sin cerrar ni borrar tus datos.</span><div class="nova20-grid">${S.v200.workspaces.map(w=>`<div class="nova20-card"><div class="row"><h3>${esc(w.icon||'◈')} ${esc(w.name)}</h3>${w.id===S.v200.activeWorkspace?'<span style="color:var(--acc)">Activo</span>':''}</div><span class="mut">${w.tabs?.length||0} pestañas guardadas</span><div class="row"><button class="btn ${w.id===S.v200.activeWorkspace?'on':''}" data-go="${esc(w.id)}">Abrir</button><button class="btn" data-ed="${esc(w.id)}">Editar</button><button class="btn" data-del="${esc(w.id)}">Eliminar</button></div></div>`).join('')}</div><button class="btn on" id="wsadd">＋ Crear espacio</button>`; r.querySelector('#wsadd').onclick=createWorkspace; r.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchWorkspace(b.dataset.go)); r.querySelectorAll('[data-ed]').forEach(b=>b.onclick=()=>renameWorkspace(b.dataset.ed)); r.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteWorkspace(b.dataset.del)); }; render(); };
  PG.workspaces = renderWorkspacesPage;
  const wsbtn=document.createElement('button');wsbtn.id='nova20-wsbtn';wsbtn.title='Espacios de trabajo';wsbtn.textContent='▦ '+ws().name;document.getElementById('brand')?.after(wsbtn);const studyBtn=document.createElement('button');studyBtn.id='nova20-studybtn';studyBtn.textContent='🎓 Estudio';studyBtn.title='Abrir Nova Study';wsbtn.after(studyBtn);
  const wspop=document.createElement('div');wspop.id='nova20-pop';document.body.appendChild(wspop);wsbtn.onclick=e=>{e.stopPropagation();refreshWorkspaceUI();wspop.classList.toggle('on')};document.addEventListener('click',e=>{if(!wspop.contains(e.target)&&e.target!==wsbtn)wspop.classList.remove('on')});

  /* ---------- Reader ---------- */
  const readerCss = `article,main,[role=main]{max-width:820px!important;margin:40px auto!important;padding:0 24px!important}body{line-height:1.8!important;font-size:19px!important}header,nav,aside,footer,[class*=ad-],[id*=banner],[class*=popup],[class*=modal]{display:none!important}img,video{max-width:100%!important;height:auto!important}`;
  N.readerToggle = () => { const t=N.activeWebTab?.()||cur; if(!t?.wv?.executeJavaScript)return; S.v200.reader=!S.v200.reader; try { t.wv.executeJavaScript(`(()=>{let s=document.getElementById('__nova20_reader');if(${S.v200.reader}){if(!s){s=document.createElement('style');s.id='__nova20_reader';s.textContent=${JSON.stringify(readerCss)};(document.head||document.documentElement).appendChild(s)}}else if(s)s.remove()})()`); } catch {} save(); $('#nova20-reader-state')?.classList.toggle('on',S.v200.reader); };

  /* ---------- Study ---------- */
  const study = { root:null, left:null, right:null, ai:null, messages:[], provider:'nova' };
  const providers = { nova:['Nova IA',''], chatgpt:['ChatGPT','https://chatgpt.com/'], gemini:['Gemini','https://gemini.google.com/'], claude:['Claude','https://claude.ai/'], perplexity:['Perplexity','https://www.perplexity.ai/'] };
  const makeAiPanel = () => { const d=document.createElement('div');d.className='nova20-study-ai';d.innerHTML=`<div class="nova20-study-head"><div class="row"><b>Nova IA</b><span class="mut">La página no se envía hasta que pides analizarla.</span></div></div><div class="nova20-study-chat" id="ns-chat"><span class="mut">Pregúntame sobre la página de la izquierda.</span></div><div class="nova20-study-compose"><input class="fld" id="ns-q" placeholder="Pregúntale a la IA…"><button class="btn on" id="ns-send">Enviar</button></div>`;const send=async()=>{const q=d.querySelector('#ns-q').value.trim();if(!q)return;d.querySelector('#ns-q').value='';const body=d.querySelector('#ns-chat');if(!study.messages.length)body.replaceChildren();study.messages.push({role:'user',content:q});body.insertAdjacentHTML('beforeend',`<div class="nova20-study-msg u">${esc(q)}</div><div class="nova20-study-msg a">…</div>`);body.scrollTop=1e9;let text='';try{text=await study.left.executeJavaScript('document.body.innerText.slice(0,16000)')}catch{};const prompt='Trabajamos en modo estudio. Esta es la página que el usuario está consultando:\n\n'+text+'\n\nPregunta del usuario: '+q;const resp=await ipc.invoke('ai-ask',{msgs:[...study.messages.slice(-10)].map(m=>({role:m.role,content:m.content})),system:'Eres Nova IA dentro de Nova Study. Ayuda a estudiar el contenido de la página de forma clara, verificable y breve. Contexto de página incluido cuando corresponda. '+prompt,model:S.model||'claude-sonnet-4-6'}).catch(e=>({error:e.message}));const ans=resp?.text||resp?.error||'No hubo respuesta.';study.messages.push({role:'assistant',content:ans});const last=body.querySelectorAll('.nova20-study-msg.a');last[last.length-1].textContent=ans;body.scrollTop=1e9;};d.querySelector('#ns-send').onclick=send;d.querySelector('#ns-q').onkeydown=e=>e.key==='Enter'&&send();return d; };
  const openStudy = provider => { const u=currentUrl(); if(!u)return toast2('Abre primero una página web.'); if(study.root) return closeStudy(); study.provider=provider||S.v200.studyProvider||'nova';S.v200.studyProvider=study.provider;save(); const root=document.createElement('div');root.id='nova20-study';root.innerHTML=`<div class="nova20-studybar"><b>🎓 Nova Study</b><span class="mut">Página actual + IA</span><select class="fld" id="ns-provider" style="width:180px">${Object.entries(providers).map(([k,v])=>`<option value="${k}" ${k===study.provider?'selected':''}>${v[0]}</option>`).join('')}</select><button class="btn" id="ns-refresh">↻ Página</button><button class="btn" id="ns-reader">📖 Lectura</button><button class="btn" id="ns-shot">📸 Captura</button><button class="btn on" id="ns-close">Cerrar</button></div><div class="nova20-study-split" id="ns-split"><div class="nova20-study-pane" id="ns-left"></div><div class="nova20-study-pane" id="ns-right"></div></div>`;document.getElementById('view').appendChild(root);study.root=root;study.left=document.createElement('webview');study.left.setAttribute('partition',profilePartition());study.left.src=u;study.left.style.cssText='display:flex;position:absolute;inset:0;width:100%;height:100%';study.right=document.createElement('webview');study.right.setAttribute('partition',profilePartition());study.right.style.cssText='display:flex;position:absolute;inset:0;width:100%;height:100%';root.querySelector('#ns-left').appendChild(study.left);root.querySelector('#ns-right').appendChild(study.right);study.ai=null;const setProvider=k=>{study.provider=k;S.v200.studyProvider=k;save();if(k==='nova'){study.right.style.display='none';root.querySelector('#ns-right').replaceChildren(makeAiPanel());root.querySelector('#ns-split').classList.remove('nova20-show-ai')}else{root.querySelector('#ns-right').replaceChildren(study.right);study.right.style.display='flex';root.querySelector('#ns-split').classList.remove('nova20-show-ai');study.right.src=providers[k][1]}};root.querySelector('#ns-provider').onchange=e=>setProvider(e.target.value);root.querySelector('#ns-close').onclick=closeStudy;root.querySelector('#ns-refresh').onclick=()=>{try{study.left.reload()}catch{}};root.querySelector('#ns-reader').onclick=()=>{try{study.left.executeJavaScript(`(()=>{let s=document.getElementById('__nova20_reader');if(!s){s=document.createElement('style');s.id='__nova20_reader';s.textContent=${JSON.stringify(readerCss)};document.head.appendChild(s)}})()`)}catch{}};root.querySelector('#ns-shot').onclick=async()=>{try{const img=await study.left.capturePage();const f=await ipc.invoke('save-shot',img.toPNG());toast2(f?'Captura guardada':'No se pudo guardar la captura')}catch{toast2('No se pudo guardar la captura')}};setProvider(study.provider);};
  const closeStudy = () => { if(!study.root)return; try{study.left?.remove()}catch{} try{study.right?.remove()}catch{} study.root.remove();study.root=null;study.left=null;study.right=null;study.messages=[]; };
  studyBtn.onclick=()=>openStudy(S.v200.studyProvider);
  N.study=openStudy;

  /* ---------- Renovación visual de bienvenida ---------- */
  const oldWelcome=PG.bienvenida;
  PG.bienvenida=async r=>{ if(typeof oldWelcome==='function') await oldWelcome(r); r.querySelector('.nova20-welcome')?.remove(); const box=document.createElement('div');box.className='nova20-welcome';box.innerHTML=`<img class="nova20-hero" src="../assets/welcome/nova20-hero.jpg" alt="Nova 2.0"><div class="nova20-release"><b style="font-size:24px;color:var(--acc)">Bienvenido a Nova 2.0.0</b><span class="mut">Una gran actualización centrada en estudio, organización, rendimiento, seguridad y una experiencia renovada.</span><div class="row" style="justify-content:flex-start;flex-wrap:wrap"><button class="btn on" id="wstudy">Abrir Nova Study</button><button class="btn" id="wws">Espacios de trabajo</button><button class="btn" id="wsec">Centro de seguridad</button><button class="btn" id="wperf">Rendimiento y RAM</button></div></div><div class="nova20-grid"><div class="nova20-chip nova20-feature"><h3>🎓 Study</h3><span class="mut">La página actual y la IA elegida en una vista dividida.</span></div><div class="nova20-chip nova20-feature"><h3>▦ Workspaces</h3><span class="mut">Guarda conjuntos de pestañas por contexto.</span></div><div class="nova20-chip nova20-feature"><h3>⚡ Rendimiento</h3><span class="mut">Más herramientas para RAM, CPU y pestañas.</span></div><div class="nova20-chip nova20-feature"><h3>🛡 Seguridad</h3><span class="mut">Diagnóstico local y controles de permisos.</span></div><div class="nova20-chip nova20-feature"><h3>♿ Accesibilidad</h3><span class="mut">Escala, contraste y reducción de movimiento.</span></div><div class="nova20-chip nova20-feature"><h3>📖 Lectura</h3><span class="mut">Modo lectura desde el menú, Command Center y Study.</span></div></div>`;r.appendChild(box);box.querySelector('#wstudy').onclick=()=>openStudy();box.querySelector('#wws').onclick=()=>newTab('nova://workspaces');box.querySelector('#wsec').onclick=()=>newTab('nova://seguridad');box.querySelector('#wperf').onclick=()=>newTab('nova://rendimiento'); };

  /* ---------- What's New renovado ---------- */
  const oldNews=PG.novedades;
  PG.novedades=r=>{if(typeof oldNews==='function')oldNews(r);const old=r.querySelector('#nova20-news-card');if(old)old.remove();const card=document.createElement('div');card.id='nova20-news-card';card.className='nova20-news';card.innerHTML=`<div class="nova20-release"><b style="font-size:24px;color:var(--acc)">Nova 2.0.0 · Gran actualización</b><span class="mut">Todo lo anterior se conserva. Esta versión añade una nueva capa sobre el navegador existente.</span><ul class="nova20-list">${[
    '🎓 Nova Study: página actual + IA elegida en vista dividida, con Nova IA integrada o proveedores web externos.',
    '▦ Espacios de trabajo: guarda y cambia conjuntos de pestañas por contexto sin mezclar sesiones.',
    '🔎 Command Center reforzado: accesos directos a Study, espacios, lectura, rendimiento, seguridad y notas.',
    '📖 Modo lectura directo para artículos y páginas con una sola acción.',
    '⚡ Rendimiento/RAM ampliado: diagnóstico local de memoria y CPU, ahorro de memoria y estado por pestaña.',
    '🛡 Seguridad reforzada: permisos, navegación segura, webviews aislados y auditoría local.',
    '♿ Accesibilidad: reducción de movimiento, alto contraste y escala de interfaz.',
    '📝 Notas, capturas y PDF: integración con Study y acciones rápidas sin eliminar las funciones anteriores.',
    '🧩 Nuevas extensiones opcionales de privacidad, rendimiento y concentración.',
    '🎨 Bienvenida e instalador renovados con identidad visual de Nova 2.0.',
    '☁ Cuenta Nova y perfiles de 1.6.5 se conservan y pueden seguir sincronizando sus datos compatibles.'
  ].map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="row" style="justify-content:flex-start;flex-wrap:wrap"><button class="btn on" id="nn-study">Study</button><button class="btn" id="nn-ws">Workspaces</button><button class="btn" id="nn-perf">Rendimiento</button><button class="btn" id="nn-sec">Seguridad</button></div></div>`;r.prepend(card);card.querySelector('#nn-study').onclick=()=>openStudy();card.querySelector('#nn-ws').onclick=()=>newTab('nova://workspaces');card.querySelector('#nn-perf').onclick=()=>newTab('nova://rendimiento');card.querySelector('#nn-sec').onclick=()=>newTab('nova://seguridad');};

  /* ---------- Accesibilidad / ajustes ---------- */
  const applyA11y=()=>{const a=S.v200.a11y||{};document.body.classList.toggle('nova20-highcontrast',!!a.highContrast);document.body.classList.toggle('nova20-reduced',!!a.reduceMotion);document.body.classList.remove('nova20-scale90','nova20-scale110','nova20-scale125');if(a.uiScale===90)document.body.classList.add('nova20-scale90');if(a.uiScale===110)document.body.classList.add('nova20-scale110');if(a.uiScale===125)document.body.classList.add('nova20-scale125');};
  const oldSet=PG.ajustes;
  PG.ajustes=r=>{ if(typeof oldSet==='function')oldSet(r); if(r.querySelector('#nova20-settings'))return;const c=document.createElement('div');c.id='nova20-settings';c.className='nova20-card';c.innerHTML=`<div class="row"><b style="color:var(--acc)">Nova 2.0</b><span class="mut">Funciones nuevas</span></div><div class="row"><span>Nova Study</span><button class="btn on" id="a-study">Abrir</button></div><div class="row"><span>Espacios de trabajo</span><button class="btn" id="a-ws">Administrar</button></div><div class="row"><span>Modo lectura</span><button class="btn ${S.v200.reader?'on':''}" id="a-read">${S.v200.reader?'Activo':'Activar'}</button></div><h3>Accesibilidad</h3><div class="row"><span>Reducir movimiento</span><div class="sw ${S.v200.a11y.reduceMotion?'on':''}" id="a-rm"></div></div><div class="row"><span>Alto contraste</span><div class="sw ${S.v200.a11y.highContrast?'on':''}" id="a-hc"></div></div><div class="row"><span>Escala de interfaz</span><select class="fld" id="a-scale" style="width:120px"><option value="90">90%</option><option value="100">100%</option><option value="110">110%</option><option value="125">125%</option></select></div><h3>Rendimiento</h3><div class="row"><span>Optimización 2.0</span><div class="sw ${S.v200.perfPlus?'on':''}" id="a-pf"></div></div><span class="mut">Conserva el throttling, reduce animaciones de interfaz y evita trabajo visual innecesario. No cierra pestañas ni borra datos.</span>`;r.appendChild(c);c.querySelector('#a-scale').value=String(S.v200.a11y.uiScale);c.querySelector('#a-study').onclick=()=>openStudy();c.querySelector('#a-ws').onclick=()=>newTab('nova://workspaces');c.querySelector('#a-read').onclick=()=>{N.readerToggle();c.querySelector('#a-read').textContent=S.v200.reader?'Activo':'Activar';c.querySelector('#a-read').classList.toggle('on',S.v200.reader)};c.querySelector('#a-rm').onclick=()=>{S.v200.a11y.reduceMotion=!S.v200.a11y.reduceMotion;save();applyA11y();c.querySelector('#a-rm').classList.toggle('on',S.v200.a11y.reduceMotion)};c.querySelector('#a-hc').onclick=()=>{S.v200.a11y.highContrast=!S.v200.a11y.highContrast;save();applyA11y();c.querySelector('#a-hc').classList.toggle('on',S.v200.a11y.highContrast)};c.querySelector('#a-scale').onchange=e=>{S.v200.a11y.uiScale=+e.target.value;save();applyA11y()};c.querySelector('#a-pf').onclick=async()=>{const next=!S.v200.perfPlus;const ok=await ipc.invoke('performance-mode',next).catch(()=>false);if(!ok)return;S.v200.perfPlus=next;save();c.querySelector('#a-pf').classList.toggle('on',next);toast2(next?'Optimización 2.0 activada':'Optimización 2.0 desactivada')}; };

  /* ---------- Menú y Command Center ---------- */
  const acts = [
    ['🎓 Nova Study',()=>openStudy()],['▦ Espacios de trabajo',()=>newTab('nova://workspaces')],['📖 Activar/desactivar modo lectura',()=>N.readerToggle()],['📊 Rendimiento y RAM',()=>newTab('nova://rendimiento')],['🛡 Auditoría de seguridad',()=>newTab('nova://seguridad')],['♿ Accesibilidad',()=>newTab('nova://ajustes')],['📝 Nueva nota',()=>newTab('nova://notas')]
  ];
  N.extraActs = Array.isArray(N.extraActs)?N.extraActs:[];for(const a of acts)if(!N.extraActs.some(x=>x[0]===a[0]))N.extraActs.push(a);
  if(Array.isArray(N.MENU)){for(const a of acts)if(!N.MENU.some(x=>x[0]===a[0]))N.MENU.push(a);const mp=document.getElementById('mnp');if(mp)mp.innerHTML=N.MENU.map((m,i)=>`<button data-i="${i}">${esc(m[0])}</button>`).join('');}

  /* ---------- Diagnóstico de rendimiento periódico, sin telemetría ---------- */
  N.performanceSnapshot = () => ipc.invoke('performance-info').catch(()=>({ok:false}));
  setInterval(()=>{ if(document.visibilityState==='visible' && S.v200.perfPlus) N.performanceSnapshot().catch(()=>{}); }, 30000);

  /* ---------- Inicio 2.0: marcar versión vista y ofrecer la pantalla renovada ---------- */
  applyA11y(); refreshWorkspaceUI();
  setTimeout(()=>{ if(S.done && S.v200.lastSeen !== NOVA_VER){ S.v200.lastSeen=NOVA_VER;save();newTab('nova://novedades'); } }, 900);
  if(!S.v200.firstRun2){ setTimeout(()=>{ if(!S.done)return; S.v200.firstRun2=true;save();newTab('nova://bienvenida'); }, 5000); }

  window.addEventListener('beforeunload',()=>{try{captureWorkspace()}catch{}});
})();
