/* Nova 2.5.0 · Air + Safari + Islands + Productivity layer */
(() => {
  const N = NOVA, { PG } = N;
  const esc25 = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cleanHttp = u => { try { const x = new URL(String(u || '')); return /^https?:$/.test(x.protocol) ? x.href : ''; } catch { return ''; } };
  const pageTitle = {
    safari:'Safari Mode', islands:'Nova Islands', glance:'Glance', focus:'Nova Focus', reader:'Nova Reader+', collections:'Colecciones', capture:'Web Capture', writer:'Nova Writer', docs:'Nova Docs', study3:'Nova Study 3', privacidad2:'Centro de privacidad', rendimiento2:'Centro de rendimiento', descargas2:'Download Hub', apps:'Web Apps', mejoras:'Mejoras de Nova', novedades:'Novedades 2.5.3'
  };
  const openPage = name => { const t = newTab('nova://' + name); setTimeout(() => { try { const sp = t?.el?.querySelector('span'); if (sp) sp.textContent = pageTitle[name] || name; } catch {} }, 30); return t; };
  const local = (rel) => `../assets/release/2.5/${rel}`;
  const IMPROVEMENTS_URL = 'nova://mejoras';
  const addStyles = () => {
    if (document.getElementById('nova25-style')) return;
    const st = document.createElement('style'); st.id = 'nova25-style'; st.textContent = `
      /* Safari surface */
      body.nova25-safari #side{width:46px;opacity:.82}body.nova25-safari #top{height:46px;padding-top:4px}body.nova25-safari #bar{background:rgba(248,248,250,.84);backdrop-filter:saturate(180%) blur(22px);border-bottom:0;padding:7px 12px}body.nova25-safari #addr{height:34px;max-width:760px;margin:0 auto;border:1px solid transparent;background:rgba(0,0,0,.055);border-radius:12px;text-align:center}body.nova25-safari #addr:focus{background:#fff;border-color:#0a84ff;box-shadow:0 0 0 3px rgba(10,132,255,.16);text-align:left}body.nova25-safari #tabs{gap:5px;padding:4px 5px 0}body.nova25-safari .tab{height:32px;border-radius:10px;flex:0 1 190px;max-width:240px;min-width:78px}body.nova25-safari .tab.on{background:rgba(255,255,255,.84);box-shadow:0 1px 2px rgba(0,0,0,.1),0 0 0 .5px rgba(0,0,0,.06)}body.nova25-safari #nt{border-radius:10px}
      #nova25-islandbar{position:absolute;top:82px;left:52px;right:0;z-index:18;display:flex;gap:6px;padding:6px 10px;pointer-events:none}.tg{height:26px;padding:0 10px;margin:0 3px 4px;border-radius:999px;background:color-mix(in srgb,var(--gc) 12%,transparent);border:1px solid color-mix(in srgb,var(--gc) 35%,var(--bd));box-shadow:none;color:var(--fg)}.tg i{width:7px;height:7px;border-radius:50%;background:var(--gc)}.tg:hover{background:color-mix(in srgb,var(--gc) 20%,transparent)}.tab.ing{border-top:0}.nova25-island{pointer-events:auto;padding:6px 10px;border-radius:999px;border:1px solid var(--bd);background:color-mix(in srgb,var(--bar) 92%,transparent);backdrop-filter:blur(16px);box-shadow:0 6px 22px #0001;font-size:11px;display:flex;gap:7px;align-items:center;cursor:pointer}.nova25-island i{width:7px;height:7px;border-radius:50%;background:var(--gc)}.nova25-island.on{border-color:var(--gc);color:var(--fg)}
      .nova25-shell{display:grid;gap:14px}.nova25-hero{width:100%;max-width:860px;border:1px solid var(--bd);border-radius:24px;display:block;box-shadow:0 18px 60px #0002}.nova25-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.nova25-card{padding:14px;border:1px solid var(--bd);background:color-mix(in srgb,var(--bar) 92%,transparent);border-radius:18px;display:flex;flex-direction:column;gap:7px;box-shadow:0 10px 30px #0001}.nova25-card img{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:12px;background:var(--bg)}
      .nova25-toolbar{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.nova25-toolbar button{min-width:38px}.nova25-editor{min-height:480px;padding:22px 24px;border:1px solid var(--bd);border-radius:18px;background:var(--bar);outline:none;line-height:1.7;font-size:16px;box-shadow:inset 0 1px 0 #fff2}.nova25-editor:focus{border-color:var(--acc);box-shadow:0 0 0 3px color-mix(in srgb,var(--acc) 18%,transparent)}.nova25-editor h1,.nova25-editor h2,.nova25-editor h3{margin:18px 0 8px}.nova25-status{display:flex;gap:12px;flex-wrap:wrap}.nova25-pill{padding:5px 9px;border:1px solid var(--bd);border-radius:999px;font-size:11px;color:var(--mut)}
      .nova25-suggestion{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding:12px 14px;border:1px solid var(--bd);border-radius:14px;background:var(--bar)}.nova25-suggestion .vote{display:flex;gap:6px;align-items:center}.nova25-vote{border:1px solid var(--bd);background:var(--bg);border-radius:999px;padding:5px 9px;cursor:pointer}.nova25-vote:hover{border-color:var(--acc);color:var(--acc)}
      .nova25-news{display:grid;gap:16px}.nova25-news .lead{display:grid;gap:8px}.nova25-news-card{display:grid;grid-template-columns:minmax(180px,260px) 1fr;gap:14px;align-items:center;padding:12px;border:1px solid var(--bd);background:var(--bar);border-radius:18px}.nova25-news-card img{width:100%;border-radius:12px;aspect-ratio:16/9;object-fit:cover}.nova25-news-card .body{display:flex;flex-direction:column;gap:6px}.nova25-news-card .body ul{margin:0;padding-left:20px}.nova25-news-card .body li{margin:4px 0}.nova25-search{display:flex;gap:8px;align-items:center}.nova25-search input{flex:1}
      .nova25-tour{position:fixed;inset:0;z-index:300;background:rgba(0,0,0,.28);backdrop-filter:blur(4px);display:grid;place-items:center}.nova25-tour .card{max-width:560px;width:min(92vw,560px);border-radius:24px;padding:24px;box-shadow:0 30px 100px #0007}.nova25-tour img{width:100%;border-radius:18px;margin-bottom:12px}.nova25-kbd{font:600 11px/1.1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;padding:4px 7px;border:1px solid var(--bd);border-bottom-width:2px;border-radius:6px;background:var(--bg)}
      .nova25-mode-chip{position:fixed;right:16px;bottom:16px;z-index:28;padding:9px 12px;border:1px solid var(--bd);background:color-mix(in srgb,var(--bar) 92%,transparent);backdrop-filter:blur(14px);border-radius:999px;box-shadow:0 10px 30px #0002}.nova25-mode-chip b{color:var(--acc)}
      body.nova25-focus #side,body.nova25-focus #panel,body.nova25-focus #brand{display:none!important}body.nova25-focus #bar{justify-content:center}body.nova25-focus #top{padding-left:12px}body.nova25-focus #tabs{max-width:720px;margin:auto}body.nova25-focus .tab:not(.on){opacity:.22}body.nova25-focus #addr{max-width:560px;margin:auto}
      @media(max-width:760px){.nova25-news-card{grid-template-columns:1fr}.nova25-editor{min-height:360px}.nova25-islandbar{left:0;overflow:auto}.nova25-island{flex:none}}
    `; document.head.appendChild(st);
  };
  addStyles();

  // ---------- Safari Mode ----------
  const safariState = () => S.nova25 = S.nova25 || { safari:false, focus:false, reader:false, autoIslands:true, collections:[], suggestions:[], docs:[] };
  safariState();
  function applySafari(){ const on=!!S.nova25.safari; document.body.classList.toggle('nova25-safari',on); S.theme = on ? 'safari' : (S.nova25.prevTheme || S.theme); save(); if(typeof applyTheme==='function') applyTheme(); }
  const oldApplyTheme = applyTheme;
  applyTheme = function(){ oldApplyTheme(); if(S.nova25?.safari) document.body.classList.add('nova25-safari'); };

  // ---------- Island bar ----------
  let islandBar;
  function refreshIslands(){
    if(!islandBar){ islandBar=document.createElement('div'); islandBar.id='nova25-islandbar'; document.body.appendChild(islandBar); }
    const groups=S.groups||{}; const entries=Object.entries(groups).filter(([id,g])=>tabs.some(t=>t.g===id));
    islandBar.innerHTML=entries.map(([id,g])=>`<button class="nova25-island ${tabs.some(t=>t.g===id&&t===cur)?'on':''}" data-g="${esc25(id)}" style="--gc:${esc25(g.color)}"><i></i><span>${esc25(g.name)}</span><small>${tabs.filter(t=>t.g===id).length}</small></button>`).join('');
    islandBar.querySelectorAll('[data-g]').forEach(b=>b.onclick=()=>{ const id=b.dataset.g; const t=tabs.find(x=>x.g===id); if(t) sel(t); });
    islandBar.style.display=entries.length?'flex':'none';
  }
  const baseRenderGroups = window.renderGroups || null;
  if(typeof baseRenderGroups==='function'){ const rg=baseRenderGroups; window.renderGroups=function(){rg();refreshIslands();}; }
  const baseSel=sel; sel=function(t){baseSel(t);refreshIslands();};
  const baseClose=closeTab; closeTab=function(t){const r=baseClose(t);setTimeout(refreshIslands,30);return r;};
  window.Nova25 = window.Nova25 || {};
  Nova25.refreshIslands=refreshIslands;

  // ---------- Pages ----------
  PG.safari = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('safari.svg')}" alt="Safari Mode"><div><h2>Safari Mode</h2><span class="mut">Una superficie inspirada en Safari, con la potencia de Nova debajo.</span></div><div class="nova25-grid"><div class="nova25-card"><b>Interfaz cristalina</b><span class="mut">Barra compacta, pestañas suaves y mucho espacio visual.</span></div><div class="nova25-card"><b>Islands</b><span class="mut">Agrupa trabajo relacionado sin convertir cada pestaña en una fila interminable.</span></div><div class="nova25-card"><b>Privacidad y rendimiento</b><span class="mut">Los centros avanzados siguen disponibles desde Command Center.</span></div></div><div class="row"><button class="btn on" id="sf-on">${S.nova25.safari?'Desactivar Safari Mode':'Activar Safari Mode'}</button><button class="btn" id="sf-is">Abrir Islands</button></div></div>`; r.querySelector('#sf-on').onclick=()=>{S.nova25.prevTheme=S.theme;if(!S.nova25.safari){S.nova25.prevTheme=S.theme==='safari'?'air':S.theme;S.nova25.safari=true;S.theme='safari';}else{S.nova25.safari=false;S.theme=S.nova25.prevTheme||'air';}save();applyTheme();r.querySelector('#sf-on').textContent=S.nova25.safari?'Desactivar Safari Mode':'Activar Safari Mode';}; r.querySelector('#sf-is').onclick=()=>openPage('islands'); };
  PG.islands = r => { const groups=S.groups||{}; r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('islands.svg')}" alt="Nova Islands"><div><h2>Nova Islands</h2><span class="mut">Tus grupos de pestañas viven como pequeñas islas: contrae, expande y mueve el conjunto.</span></div><div class="nova25-grid">${Object.entries(groups).map(([id,g])=>`<div class="nova25-card"><b>${esc25(g.name)}</b><span class="mut">${tabs.filter(t=>t.g===id).length} pestaña(s) · ${g.collapsed?'contraída':'visible'}</span><div class="row"><button class="btn" data-open="${esc25(id)}">Abrir</button><button class="btn" data-collapse="${esc25(id)}">${g.collapsed?'Expandir':'Contraer'}</button></div></div>`).join('')||'<span class="mut">Aún no hay Islands. En una pestaña: clic derecho → Mover a grupo → Nuevo grupo.</span>'}</div><div class="row"><button class="btn on" id="is-auto">${S.nova25.autoIslands?'Sugerencias automáticas: activadas':'Sugerencias automáticas: desactivadas'}</button><button class="btn" id="is-new">Nueva Island</button></div></div>`; r.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const t=tabs.find(x=>x.g===b.dataset.open);if(t)sel(t);});r.querySelectorAll('[data-collapse]').forEach(b=>b.onclick=()=>{const g=groups[b.dataset.collapse];if(!g)return;g.collapsed=!g.collapsed;save();refreshIslands();PG.islands(r)}); r.querySelector('#is-auto').onclick=()=>{S.nova25.autoIslands=!S.nova25.autoIslands;save();PG.islands(r)}; r.querySelector('#is-new').onclick=()=>{if(!cur)return;const name=(prompt('Nombre de la Island','Nueva Island')||'').trim();if(!name)return;S.groups=S.groups||{};const id='g'+Date.now().toString(36);S.groups[id]={name,color:'#0a84ff',collapsed:false};cur.g=id;save();refreshIslands();PG.islands(r);toast('Island creada.');}; };

  PG.glance = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('glance.svg')}" alt="Glance"><h2>Glance</h2><span class="mut">Previsualiza un enlace sin convertirlo todavía en una pestaña completa.</span><div class="nova25-card"><b>Cómo usarlo</b><span class="mut">Mantén <span class="nova25-kbd">Alt</span> y haz clic en un enlace. También puedes usar el gesto desde Command Center.</span></div><button class="btn on" id="gl-start">Probar con la pestaña actual</button></div>`; r.querySelector('#gl-start').onclick=()=>toast('Glance: usa Alt + clic sobre un enlace.'); };

  PG.focus = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('focus.svg')}" alt="Nova Focus"><h2>Nova Focus</h2><span class="mut">Una capa silenciosa para trabajar sin convertir Nova en una app de productividad.</span><div class="nova25-grid"><div class="nova25-card"><b>25 min</b><span class="mut">Enfoque rápido.</span><button class="btn on" data-min="25">Iniciar</button></div><div class="nova25-card"><b>50 min</b><span class="mut">Sesión profunda.</span><button class="btn" data-min="50">Iniciar</button></div><div class="nova25-card"><b>Personalizado</b><input class="fld" id="fm" type="number" min="1" max="240" value="35"><button class="btn" id="fc">Iniciar</button></div></div><div class="nova25-status"><span class="nova25-pill">Interfaz mínima</span><span class="nova25-pill">Pestañas secundarias atenuadas</span><span class="nova25-pill">Temporizador local</span></div></div>`; const start=m=>{S.nova25.focus=true;save();document.body.classList.add('nova25-focus');const chip=document.createElement('div');chip.className='nova25-mode-chip';chip.id='nova25-focus-chip';let sec=Math.max(60,m*60),int=setInterval(()=>{sec--;chip.innerHTML=`✦ <b>Focus</b> · ${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')} <button class="btn" id="fx25">Salir</button>`;chip.querySelector('#fx25').onclick=()=>{clearInterval(int);chip.remove();S.nova25.focus=false;document.body.classList.remove('nova25-focus');save()};if(sec<=0){clearInterval(int);toast('Sesión de Focus terminada');chip.remove();document.body.classList.remove('nova25-focus');S.nova25.focus=false;save()}},1000);chip.innerHTML=`✦ <b>Focus</b> · ${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')} <button class="btn" id="fx25">Salir</button>`;document.body.appendChild(chip);chip.querySelector('#fx25').onclick=()=>{clearInterval(int);chip.remove();S.nova25.focus=false;document.body.classList.remove('nova25-focus');save()};}; r.querySelectorAll('[data-min]').forEach(b=>b.onclick=()=>start(+b.dataset.min));r.querySelector('#fc').onclick=()=>start(Math.max(1,+r.querySelector('#fm').value||35)); };

  PG.reader = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('reader.svg')}" alt="Reader+"><h2>Nova Reader+</h2><span class="mut">Ajusta la lectura de la página actual o abre una vista limpia del contenido.</span><div class="nova25-grid"><div class="nova25-card"><b>Tipografía</b><span class="mut">Georgia / Segoe / sistema</span></div><div class="nova25-card"><b>Ancho</b><span class="mut">Línea cómoda de 60–80 caracteres.</span></div><div class="nova25-card"><b>Sin distracciones</b><span class="mut">Oculta elementos secundarios en la web actual.</span></div></div><div class="row"><button class="btn on" id="rd-on">Aplicar a esta página</button><button class="btn" id="rd-reset">Quitar</button></div></div>`; const css=`body{max-width:820px!important;margin:0 auto!important;background:#fff!important}header,nav,aside,footer,[class*=ad-],[id*=banner],[role=banner]{display:none!important}body{font:18px/1.8 Georgia,serif!important}img,video{max-width:100%!important;height:auto!important}`;r.querySelector('#rd-on').onclick=()=>{try{cur.wv.executeJavaScript(`(()=>{let s=document.getElementById('__nova25_reader');if(!s){s=document.createElement('style');s.id='__nova25_reader';s.textContent=${JSON.stringify(css)};document.head.appendChild(s)}})()`);toast('Reader+ aplicado')}catch{toast('No se pudo aplicar Reader+')}};r.querySelector('#rd-reset').onclick=()=>{try{cur.wv.executeJavaScript("document.getElementById('__nova25_reader')?.remove()") }catch{}}; };

  PG.collections = r => { const a=S.nova25.collections||[]; r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('collections.svg')}" alt="Colecciones"><h2>Colecciones</h2><span class="mut">Guarda páginas, notas y documentos por proyecto.</span><div class="row"><input class="fld" id="cn25" placeholder="Nueva colección"><button class="btn on" id="ca25">Crear</button></div><div id="cl25" class="nova25-grid"></div></div>`; const draw=()=>{r.querySelector('#cl25').innerHTML=(S.nova25.collections||[]).map((c,i)=>`<div class="nova25-card"><b>${esc25(c.name)}</b><span class="mut">${c.items?.length||0} elementos</span><div class="row"><button class="btn" data-open="${i}">Abrir</button><button class="btn" data-del="${i}">Eliminar</button></div></div>`).join('')||'<span class="mut">Crea tu primera colección.</span>';r.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{S.nova25.collections.splice(+b.dataset.del,1);save();draw()});};r.querySelector('#ca25').onclick=()=>{const n=r.querySelector('#cn25').value.trim();if(!n)return;S.nova25.collections.push({name:n,items:[]});save();r.querySelector('#cn25').value='';draw();};draw(); };

  PG.capture = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('capture.svg')}" alt="Web Capture"><h2>Web Capture</h2><span class="mut">Captura la pestaña actual y envíala a Notas, Writer o tu carpeta de Descargas.</span><div class="row"><button class="btn on" id="cp25">Capturar pantalla</button><button class="btn" id="cpclip">Capturar y copiar</button></div><span class="mut" id="cps"></span></div>`;r.querySelector('#cp25').onclick=async()=>{try{const img=await cur.wv.capturePage();const f=await ipc.invoke('save-shot',img.toPNG());r.querySelector('#cps').textContent=f?'Guardado en '+f:'No se pudo guardar';}catch(e){r.querySelector('#cps').textContent='Error: '+e.message}};r.querySelector('#cpclip').onclick=async()=>{try{const img=await cur.wv.capturePage();require('electron').clipboard.writeImage(img);r.querySelector('#cps').textContent='Captura copiada al portapapeles.'}catch{}}; };

  function blocksFromHtml(html){ const tmp=document.createElement('div'); tmp.innerHTML=html; const out=[]; const walk=(node,style)=>{if(node.nodeType===3){if(node.textContent)style.runs.push({t:node.textContent,b:style.b,i:style.i});return;} if(node.nodeType!==1)return; const tag=node.tagName.toLowerCase(); if(['p','div','h1','h2','h3','li'].includes(tag)){if(style.runs.length)out.push({tag:style.tag,runs:style.runs});style={tag:['h1','h2','h3'].includes(tag)?tag:'p',runs:[],b:false,i:false}; if(tag==='li')style.runs.push({t:'• ',b:false,i:false});} const ns={tag:style.tag,runs:style.runs,b:style.b,i:style.i}; if(tag==='strong'||tag==='b')ns.b=true;if(tag==='em'||tag==='i')ns.i=true;node.childNodes.forEach(ch=>walk(ch,ns)); if(['p','div','h1','h2','h3','li'].includes(tag)&&ns.runs.length){out.push({tag:ns.tag,runs:ns.runs});style={tag:'p',runs:[],b:false,i:false};}}; walk(tmp,{tag:'p',runs:[],b:false,i:false});if(!out.length)out.push({tag:'p',runs:[{t:tmp.textContent||'',b:false,i:false}]});return out; }
  function xmlEsc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
  function buildDocXml(title, html){ const blocks=blocksFromHtml(html); return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${blocks.map(b=>`<w:p>${b.tag!=='p'?`<w:pPr><w:pStyle w:val="${b.tag}"/></w:pPr>`:''}${b.runs.map(run=>`<w:r><w:rPr>${run.b?'<w:b/>':''}${run.i?'<w:i/>':''}</w:rPr><w:t xml:space="preserve">${xmlEsc(run.t)}</w:t></w:r>`).join('')}</w:p>`).join('')}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`; }
  PG.writer = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('writer.svg')}" alt="Nova Writer"><div class="row"><div><h2 style="margin:0">Nova Writer</h2><span class="mut">Escribe en Nova y exporta un Word real.</span></div><span style="margin-left:auto" class="nova25-pill" id="wc25">0 palabras</span></div><div class="nova25-toolbar"><button class="btn" data-cmd="bold"><b>B</b></button><button class="btn" data-cmd="italic"><i>I</i></button><button class="btn" data-cmd="formatBlock" data-val="h1">H1</button><button class="btn" data-cmd="formatBlock" data-val="h2">H2</button><button class="btn" data-cmd="insertUnorderedList">• Lista</button><button class="btn" data-cmd="createLink">🔗</button><span style="flex:1"></span><button class="btn" id="wdl">Descargar .docx</button><button class="btn on" id="wnew">Nuevo</button></div><div class="nova25-editor" id="we" contenteditable="true"><h1>Nuevo documento</h1><p>Empieza a escribir aquí…</p></div><div class="mut">Guardado local en este perfil. Exportación Word sin salir de Nova.</div></div>`;const ed=r.querySelector('#we');const update=()=>{r.querySelector('#wc25').textContent=(ed.innerText.trim().match(/\S+/g)||[]).length+' palabras';S.nova25.lastDoc={title:(ed.querySelector('h1')?.innerText||'Documento'),html:ed.innerHTML};save()};r.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{const c=b.dataset.cmd;if(c==='createLink'){const u=prompt('Dirección del enlace','https://');if(u)document.execCommand(c,false,u)}else document.execCommand(c,false,b.dataset.val||null);ed.focus();update()});r.querySelector('#wnew').onclick=()=>{ed.innerHTML='<h1>Nuevo documento</h1><p></p>';update();ed.focus()};ed.oninput=update;r.querySelector('#wdl').onclick=async()=>{const title=(ed.querySelector('h1')?.innerText||'Nova Documento').trim().slice(0,80)||'Nova Documento';const xml=buildDocXml(title,ed.innerHTML);const f=await ipc.invoke('save-docx',{title,documentXml:xml}).catch(()=>null);toast(f?'Word guardado en '+f:'No se pudo guardar el Word');};update();};

  PG.docs = r => { const d=S.nova25.lastDoc; r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('docs.svg')}" alt="Nova Docs"><h2>Nova Docs</h2><span class="mut">Tu espacio de documentos locales.</span><div class="nova25-card"><b>${esc25(d?.title||'Sin documento reciente')}</b><span class="mut">${d?'Documento guardado desde Writer.':'Abre Writer para crear uno.'}</span><div class="row"><button class="btn on" id="do-write">Abrir Writer</button>${d?'<button class="btn" id="do-export">Exportar de nuevo</button>':''}</div></div></div>`;r.querySelector('#do-write').onclick=()=>openPage('writer'); if(d&&r.querySelector('#do-export'))r.querySelector('#do-export').onclick=async()=>{const f=await ipc.invoke('save-docx',{title:d.title||'Nova Documento',documentXml:buildDocXml(d.title,d.html)}).catch(()=>null);toast(f?'Word guardado en '+f:'No se pudo guardar el Word')}; };

  PG.study3 = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('study.svg')}" alt="Nova Study 3"><h2>Nova Study 3</h2><span class="mut">Une la pestaña actual, Reader+, notas y Writer en una sola sesión.</span><div class="row"><button class="btn on" id="sy-read">Aplicar Reader+</button><button class="btn" id="sy-wr">Abrir Writer</button><button class="btn" id="sy-col">Guardar en Colecciones</button></div><div class="nova25-card"><b>Flujo sugerido</b><span class="mut">1. Lee · 2. resume · 3. guarda · 4. escribe · 5. exporta.</span></div></div>`;r.querySelector('#sy-read').onclick=()=>openPage('reader');r.querySelector('#sy-wr').onclick=()=>openPage('writer');r.querySelector('#sy-col').onclick=()=>openPage('collections'); };

  PG.privacidad2 = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('privacy.svg')}" alt="Privacy Center"><h2>Centro de privacidad</h2><span class="mut">Un único sitio para ver las protecciones de Nova.</span><div class="nova25-grid"><div class="nova25-card"><b>Bloqueador</b><span class="mut">${S.adblock?'Activo':'Desactivado'}</span><button class="btn" id="pv-ad">Cambiar</button></div><div class="nova25-card"><b>Datos</b><span class="mut">Historial, cookies y caché.</span><button class="btn" id="pv-clear">Limpiar</button></div><div class="nova25-card"><b>Webview</b><span class="mut">Webviews con Node Integration desactivado.</span></div></div></div>`;r.querySelector('#pv-ad').onclick=()=>{S.adblock=!S.adblock;save();applyTheme();PG.privacidad2(r)};r.querySelector('#pv-clear').onclick=async()=>{S.hist=[];save();await ipc.invoke('clear');toast('Datos de navegación limpiados');}; };

  PG.rendimiento2 = async r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('performance.svg')}" alt="Performance Center"><h2>Centro de rendimiento</h2><span class="mut">RAM, procesos web y modo ahorro en un mismo sitio.</span><div class="nova25-card" id="pi25">Consultando…</div><div class="row"><button class="btn on" id="pf25">Alternar ahorro de memoria</button><button class="btn" id="pc25">Limpiar caché</button></div></div>`;const pi=r.querySelector('#pi25');const paint=async()=>{const d=await ipc.invoke('performance-info').catch(()=>({ok:false}));pi.innerHTML=d?.ok?`<div class="nova25-status"><span class="nova25-pill">Pestañas web: ${d.webviewCount??'—'}</span><span class="nova25-pill">PID: ${d.pid??'—'}</span><span class="nova25-pill">Memoria: ${d.memoryMB??'—'} MB</span></div>`:'No disponible';};r.querySelector('#pf25').onclick=async()=>{const on=!S.nova25.perf;const ok=await ipc.invoke('performance-mode',on).catch(()=>false);if(ok){S.nova25.perf=on;save();toast(on?'Ahorro activo':'Ahorro desactivado')}};r.querySelector('#pc25').onclick=async()=>{const ok=await ipc.invoke('performance-cache').catch(()=>false);toast(ok?'Caché limpiada':'No se pudo limpiar la caché');paint()};paint(); };

  PG.descargas2 = r => { r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('downloads.svg')}" alt="Download Hub"><h2>Download Hub</h2><span class="mut">Acceso rápido a tus descargas y a la carpeta de archivos.</span><div class="nova25-card"><b>${(S.dls||[]).length} descargas registradas</b><span class="mut">Usa el gestor existente para pausar o abrir archivos.</span><div class="row"><button class="btn on" id="dh-open">Abrir Descargas</button><button class="btn" id="dh-folder">Abrir carpeta</button></div></div></div>`;r.querySelector('#dh-open').onclick=()=>newTab('nova://descargas');r.querySelector('#dh-folder').onclick=()=>ipc.invoke('open-external',`file://${require('os').homedir()}/Downloads`).catch(()=>{}); };

  PG.apps = r => { const apps=Array.isArray(S.nova25.apps)?S.nova25.apps:[]; r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('apps.svg')}" alt="Web Apps"><h2>Web Apps</h2><span class="mut">Guarda webs como accesos rápidos de Nova.</span><div class="row"><input class="fld" id="an25" placeholder="https://ejemplo.com"><input class="fld" id="at25" placeholder="Nombre"><button class="btn on" id="aa25">Añadir</button></div><div class="nova25-grid">${apps.map((a,i)=>`<div class="nova25-card"><b>${esc25(a.name)}</b><span class="mut">${esc25(a.url)}</span><div class="row"><button class="btn on" data-app="${i}">Abrir</button><button class="btn" data-delapp="${i}">Eliminar</button></div></div>`).join('')||'<span class="mut">Añade tu primera web app.</span>'}</div></div>`;r.querySelector('#aa25').onclick=()=>{const u=cleanHttp(r.querySelector('#an25').value);const n=r.querySelector('#at25').value.trim()||u;if(!u)return toast('Escribe una URL HTTP o HTTPS');S.nova25.apps.push({url:u,name:n});save();PG.apps(r)};r.querySelectorAll('[data-app]').forEach(b=>b.onclick=()=>newTab(apps[+b.dataset.app].url));r.querySelectorAll('[data-delapp]').forEach(b=>b.onclick=()=>{S.nova25.apps.splice(+b.dataset.delapp,1);save();PG.apps(r)}); };

  PG.mejoras = r => { const seeded=[
    ['Islands inteligentes','Sugerencias automáticas cuando varias pestañas pertenecen al mismo proyecto.','Pestañas'],
    ['Reader con perfiles','Guardar tipografía, ancho y tema por sitio.','Lectura'],
    ['Plantillas de Writer','Cartas, CV, apuntes y trabajos con un clic.','Writer']
  ]; S.nova25.suggestions = S.nova25.suggestions || seeded.map(x=>({title:x[0],text:x[1],cat:x[2],votes:0})); const draw=()=>{r.querySelector('#ml25').innerHTML=S.nova25.suggestions.map((s,i)=>`<div class="nova25-suggestion"><div><b>${esc25(s.title)}</b><div class="mut">${esc25(s.cat)} · ${esc25(s.text)}</div></div><div class="vote"><span class="nova25-pill">${s.votes||0}</span><button class="nova25-vote" data-v="${i}">▲</button></div></div>`).join('')}; r.innerHTML=`<div class="nova25-shell"><img class="nova25-hero" src="${local('improvements.svg')}" alt="Mejoras de Nova"><div><h2>Mejoras de Nova</h2><span class="mut">Un sitio dentro del navegador para contarme qué mejorar, votar ideas y guardar propuestas.</span></div><div class="nova25-card"><div class="row"><input class="fld" id="mt25" placeholder="Título de la mejora"><select class="fld" id="mc25" style="max-width:180px"><option>Pestañas</option><option>Interfaz</option><option>IA</option><option>Writer</option><option>Privacidad</option><option>Rendimiento</option><option>Otro</option></select></div><textarea class="fld" id="md25" rows="4" placeholder="¿Qué debería hacer Nova mejor?"></textarea><div class="row"><button class="btn on" id="ma25">Guardar mejora</button><button class="btn" id="mg25">Abrir GitHub Issues</button></div></div><div id="ml25" class="nova25-shell"></div></div>`;r.querySelector('#ma25').onclick=()=>{const t=r.querySelector('#mt25').value.trim(),d=r.querySelector('#md25').value.trim(),c=r.querySelector('#mc25').value;if(!t||!d)return toast('Añade un título y una descripción');S.nova25.suggestions.push({title:t,text:d,cat:c,votes:0});save();r.querySelector('#mt25').value='';r.querySelector('#md25').value='';draw()};r.querySelector('#mg25').onclick=()=>ipc.invoke('open-external','https://github.com/sdraiky99/NovaBrowser/issues/new').catch(()=>{});r.addEventListener('click',e=>{const b=e.target.closest('[data-v]');if(!b)return;S.nova25.suggestions[+b.dataset.v].votes=(S.nova25.suggestions[+b.dataset.v].votes||0)+1;save();draw()});draw(); };

  PG.novedades = r => { const cards=[
    ['safari.svg','Safari Mode','Superficie limpia tipo Safari con la potencia de Nova.'],
    ['islands.svg','Nova Islands','Los grupos de pestañas pasan a ser espacios visuales compactos.'],
    ['glance.svg','Glance','Previsualiza enlaces sin abrir una pestaña completa.'],
    ['focus.svg','Nova Focus','Concentración rápida con temporizador y UI mínima.'],
    ['reader.svg','Nova Reader+','Lectura cómoda y configurable.'],
    ['collections.svg','Colecciones','Agrupa enlaces y proyectos por contexto.'],
    ['capture.svg','Web Capture','Captura y envía páginas a tus herramientas.'],
    ['writer.svg','Nova Writer','Editor integrado con exportación DOCX.'],
    ['docs.svg','Nova Docs','Gestor local de documentos creados en Nova.'],
    ['study.svg','Nova Study 3','Web + lectura + escritura en un mismo flujo.'],
    ['privacy.svg','Centro de privacidad','Todos los controles importantes en un solo lugar.'],
    ['performance.svg','Centro de rendimiento','Memoria, CPU y caché reunidos.'],
    ['downloads.svg','Download Hub','Descargas más accesibles y organizadas.'],
    ['apps.svg','Web Apps','Accesos a tus aplicaciones web dentro de Nova.'],
    ['setup.svg','Setup renovado','Instalador más claro, rápido y ligero.'],
    ['onboarding.svg','Nuevo inicio','Bienvenida guiada en menos pasos.'],
    ['improvements.svg','Mejoras de Nova','Tu sitio interno para propuestas y feedback.']
  ]; r.innerHTML=`<div class="nova25-news"><div class="lead"><h2>Nova 2.5.3</h2><span class="mut">Air + Safari + Islands + productividad. Muchas funciones nuevas, una superficie más tranquila.</span><div class="row"><button class="btn on" id="nsv">Safari Mode</button><button class="btn" id="nwr">Writer</button><button class="btn" id="nfb">Mejoras</button></div></div>${cards.map(([im,t,d])=>`<article class="nova25-news-card"><img src="${local(im)}" alt="${esc25(t)}"><div class="body"><b style="font-size:18px">${esc25(t)}</b><span class="mut">${esc25(d)}</span><div class="row"><span class="nova25-pill">Nueva</span></div></div></article>`).join('')}</div>`; r.querySelector('#nsv').onclick=()=>openPage('safari');r.querySelector('#nwr').onclick=()=>openPage('writer');r.querySelector('#nfb').onclick=()=>newTab(IMPROVEMENTS_URL); };

  // ---------- Command Center additions ----------
  if(Array.isArray(N.extraActs)){
    const extras=[
      ['Safari Mode',()=>openPage('safari')],['Nova Islands',()=>openPage('islands')],['Glance',()=>openPage('glance')],['Nova Focus',()=>openPage('focus')],['Nova Reader+',()=>openPage('reader')],['Colecciones',()=>openPage('collections')],['Web Capture',()=>openPage('capture')],['Nova Writer',()=>openPage('writer')],['Nova Docs',()=>openPage('docs')],['Nova Study 3',()=>openPage('study3')],['Centro de privacidad',()=>openPage('privacidad2')],['Centro de rendimiento',()=>openPage('rendimiento2')],['Download Hub',()=>openPage('descargas2')],['Web Apps',()=>openPage('apps')],['Mejoras de Nova',()=>newTab(IMPROVEMENTS_URL)]
    ]; extras.forEach(a=>{if(!N.extraActs.some(x=>x[0]===a[0]))N.extraActs.push(a)});
  }

  // ---------- Automatic Island suggestion from repeated domain ----------
  function suggestIsland(){ if(!S.nova25.autoIslands||!cur?.wv||cur.wv.tagName!=='WEBVIEW')return; let host='';try{host=new URL(cur.wv.getURL()).hostname}catch{return}if(!host)return;const same=tabs.filter(t=>{try{return t!==cur&&new URL(t.wv.getURL()).hostname===host}catch{return false}});if(same.length<1)return;if(same.some(t=>t.g))return;const key='suggested-'+host; if((S.nova25.suggested||{})[key])return; S.nova25.suggested=S.nova25.suggested||{}; S.nova25.suggested[key]=1;save();setTimeout(()=>{if(confirm(`Nova ha detectado ${same.length+1} pestañas de ${host}. ¿Crear una Island?`)){S.groups=S.groups||{};const id='g'+Date.now().toString(36);S.groups[id]={name:host.replace(/^www\./,''),color:'#0a84ff',collapsed:false};[cur,...same].forEach(t=>t.g=id);save();typeof Nova25.refreshIslands==='function'&&Nova25.refreshIslands();toast('Island creada.')}},150); }
  tabs.forEach(t=>{try{t.wv?.addEventListener?.('did-stop-loading',suggestIsland)}catch{}});

  // ---------- Link Glance (Alt+click) ----------
  const glancePfx='__N25GL__';
  function injectGlance(t){ if(!t?.wv||t.wv.tagName!=='WEBVIEW')return; const code=`(()=>{if(window.__n25g)return;window.__n25g=1;document.addEventListener('click',e=>{if(!e.altKey)return;const a=e.target?.closest?.('a[href]');if(!a)return;let u='';try{u=new URL(a.href).href}catch{}if(!/^https?:$/.test(new URL(u).protocol))return;e.preventDefault();e.stopPropagation();console.log(${JSON.stringify(glancePfx)}+JSON.stringify({u}));},true)})()`; t.wv.executeJavaScript(code).catch(()=>{}); }
  const wireGlance = t => { if(!t?.wv || t.wv.tagName!=='WEBVIEW' || t._n25gl) return; t._n25gl=1; injectGlance(t); try{ t.wv.addEventListener('dom-ready',()=>injectGlance(t)); t.wv.addEventListener('console-message',e=>{ if(String(e.message||'').startsWith(glancePfx)){ let m; try{m=JSON.parse(e.message.slice(glancePfx.length))}catch{return} showGlance(t,m.u); } }); }catch{} };
  tabs.forEach(wireGlance);
  const baseNewTab25 = newTab;
  newTab = function(u){ const t=baseNewTab25(u); setTimeout(()=>{wireGlance(t); if(t?.wv?.tagName==='WEBVIEW'&&!t._n25auto){t._n25auto=1;try{t.wv.addEventListener('did-stop-loading',suggestIsland)}catch{}}},80); return t; };
  function showGlance(t,u){
    const ov=document.createElement('div');ov.className='nova25-tour';ov.id='nova25-glance';ov.innerHTML=`<div class="card" style="max-width:880px"><div class="row"><div><b>Glance</b><div class="mut">${esc25(u)}</div></div><button class="btn" id="gx">Cerrar</button></div><div style="margin-top:10px;height:62vh;max-height:640px;border:1px solid var(--bd);border-radius:16px;overflow:hidden"><webview id="gweb" partition="${typeof profilePartition==='function'?esc25(profilePartition()):'persist:nova-default'}" src="${esc25(u)}" style="display:flex;width:100%;height:100%"></webview></div><div class="row" style="margin-top:10px"><button class="btn on" id="go-open">Abrir en pestaña</button><button class="btn" id="go-is">Abrir y añadir a Island</button></div></div>`;document.body.appendChild(ov);ov.querySelector('#gx').onclick=()=>ov.remove();ov.querySelector('#go-open').onclick=()=>{ov.remove();newTab(u)};ov.querySelector('#go-is').onclick=()=>{ov.remove();const nt=newTab(u);setTimeout(()=>{const id=t.g||(()=>{const id='g'+Date.now().toString(36);S.groups[id]={name:new URL(u).hostname,color:'#0a84ff',collapsed:false};return id})();nt.g=id;save();refreshIslands()},100)};
  }

  // ---------- Keep current + button behavior and reset tab spacing ----------
  if(typeof keepTabAddAtEnd==='function') keepTabAddAtEnd();
  refreshIslands();

  // ---------- Setup / welcome state ----------
  N.openFirstRun = () => { S.nova25.forceIntro=1; save(); openPage('bienvenida'); };
  // Make the dedicated internal welcome richer without breaking the original flow.
  PG.bienvenida = r => { r.innerHTML=`<div class="nova25-shell"><img src="${local('onboarding.svg')}" class="nova25-hero" alt="Nova 2.5 onboarding"><div><h2>Bienvenido a Nova 2.5.3</h2><span class="mut">Air en la superficie; Safari, Islands, Focus y herramientas potentes cuando las necesitas.</span></div><div class="nova25-grid"><div class="nova25-card"><b>⌘ Organiza</b><span class="mut">Spaces para contexto, Islands para proyectos y pestañas para páginas.</span></div><div class="nova25-card"><b>✦ Concéntrate</b><span class="mut">Focus y Reader+ aparecen solo cuando los necesitas.</span></div><div class="nova25-card"><b>✎ Crea</b><span class="mut">Writer convierte tus ideas en documentos Word.</span></div><div class="nova25-card"><b>↑ Mejora</b><span class="mut">Cuéntanos qué debería mejorar Nova desde nova://mejoras.</span></div></div><div class="row" style="flex-wrap:wrap"><button class="btn on" id="nb-sf">Safari Mode</button><button class="btn" id="nb-is">Islands</button><button class="btn" id="nb-wr">Writer</button><button class="btn" id="nb-fc">Focus</button><button class="btn" id="nb-mm">Mejoras</button></div></div>`;r.querySelector('#nb-sf').onclick=()=>openPage('safari');r.querySelector('#nb-is').onclick=()=>openPage('islands');r.querySelector('#nb-wr').onclick=()=>openPage('writer');r.querySelector('#nb-fc').onclick=()=>openPage('focus');r.querySelector('#nb-mm').onclick=()=>newTab(IMPROVEMENTS_URL); };

  // ---------- Setup clean-up / add feedback to menu ----------
  if(Array.isArray(MENU)){ if(!MENU.some(m=>m[0]==='Mejoras de Nova')) MENU.push(['Mejoras de Nova',()=>newTab(IMPROVEMENTS_URL)]); if(!MENU.some(m=>m[0]==='Safari Mode')) MENU.push(['Safari Mode',()=>openPage('safari')]); }
  // ---------- One-click shortcut hints ----------
  if(typeof N.SHORTCUTS==='object'&&Array.isArray(N.SHORTCUTS)){ N.SHORTCUTS.push(['Alt + clic','Glance · previsualizar enlace'],['Ctrl + K','Command Center · acciones y páginas'],['Ctrl + Shift + N','Nueva Island desde la pestaña actual']); }
  document.addEventListener('keydown',e=>{ if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='n'){e.preventDefault();if(cur){if(typeof newGroup==='function')newGroup(cur);}} });

  // ---------- Smooth default: Air but not forced if user chose another theme ----------
  if(!S.nova25.initialized){ S.nova25.initialized=1; if(!S.theme||S.theme==='air'){S.theme='air';save();} }
})();
