'use strict';
const fs=require('fs');
const path=require('path');
const assert=require('assert');
const vm=require('vm');
const root=path.resolve(__dirname,'..');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
const pkg=JSON.parse(read('package.json'));
const ok=m=>console.log('OK',m);
assert.strictEqual(pkg.version,'5.5.1');
assert.ok(pkg.build.files.includes('shell/**')&&pkg.build.files.includes('assets/**'));
assert.ok(pkg.build.nsis.uninstallDisplayName.includes('5.5.1'));ok('metadatos y empaquetado Next-Gen');
const all=[];(function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){if(['node_modules','.git','dist'].includes(e.name))continue;const f=path.join(d,e.name);if(e.isDirectory())walk(f);else all.push(path.relative(root,f));}})(root);
assert.ok(all.length<100,`inventario del proyecto: ${all.length} archivos`);ok(`inventario conservado (${all.length} archivos)`);
const relnotes=all.filter(f=>/^RELEASE_NOTES_.*\.md$/i.test(path.basename(f))&&path.dirname(f)==='.');
assert.deepStrictEqual(relnotes,['RELEASE_NOTES_5.5.1.md']);
assert.ok(fs.existsSync(path.join(root,'docs/history/5.4.1.md')));assert.ok(fs.existsSync(path.join(root,'docs/history/RELEASE_NOTES_5.5.0.md')));assert.ok(fs.existsSync(path.join(root,'docs/history/qa-5.5.0.js')));ok('notas actuales separadas e historial anterior conservado');
const main=read('main.js'), renderer=read('shell/nova.js'), home=read('shell/newtab.html'), preload=read('shell/newtab-preload.js'), css=read('shell/nova.css'), splash=read('shell/splash.html');
for(const action of ['toolbar-wallpaper-pick','toolbar-wallpaper-clear'])assert.ok(main.includes(action),`falta IPC ${action}`);
assert.ok(main.includes('12 * 1024 * 1024')&&main.includes('validPng')&&main.includes('validJpeg')&&main.includes('validWebp'));
assert.ok(renderer.includes('function toolbarWallpaperUrl()')&&renderer.includes('pickWallpaper')&&renderer.includes('resetWallpaper'));
assert.ok(css.includes('--toolbar-wallpaper')&&css.includes('.wallpaper-preview')&&css.includes('prefers-reduced-motion'));
assert.ok(preload.includes('open-whats-new')&&home.includes('Nova 5.5.1 · Next-Gen'));assert.ok(home.includes('.release-note{')&&home.includes('.shortcut-icon{'));assert.ok(splash.includes('NEXT-GEN · 5.5.1')&&!splash.includes('QUANTUM 5.3.3'));ok('fondo local validado, identidad Next-Gen, controles de apariencia y novedades enlazadas');
const inline=[...home.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).filter(x=>x.trim());assert.ok(inline.length);inline.forEach((x,i)=>new vm.Script(x,{filename:`newtab-inline-${i+1}.js`}));ok('scripts inline de nueva pestaña compilan');
assert.ok(main.includes('wp.nodeIntegration = false;')&&main.includes('wp.contextIsolation = true;')&&main.includes('wp.sandbox = true;'));
assert.ok(main.includes('isTrustedNewTabContents(e.sender)'));assert.ok(!/require\(['"]electron['"]\)/.test(home));
const {resolveNavigation}=require('../shell/navigation.js');
const cases=[['https://example.com/a','https://example.com/a'],['example.com','https://example.com/'],['example.com:8443/docs?q=test','https://example.com:8443/docs?q=test'],['localhost:3000','http://localhost:3000/'],['127.0.0.1:8080/path','http://127.0.0.1:8080/path'],['[::1]:5173','http://[::1]:5173/'],['hola mundo','https://www.google.com/search?q=hola%20mundo'],['javascript:alert(1)','https://www.google.com/search?q=javascript%3Aalert(1)'],['','']];
for(const [input,expected] of cases)assert.strictEqual(resolveNavigation(input),expected,input);assert.strictEqual(resolveNavigation('privado','https://duckduckgo.com/?q='),'https://duckduckgo.com/?q=privado');assert.ok(resolveNavigation('privado','javascript:alert(1)').startsWith('https://www.google.com/search?q='));ok(`${cases.length+2} casos de navegación`);
for(const rel of ['shell/index.html','shell/newtab.html','shell/newtab-preload.js','shell/navigation.js','shell/nova.js','shell/nova.css','main.js','build/installer.nsh','assets/brand/nova.ico','assets/brand/nova-icon.png'])assert.ok(fs.existsSync(path.join(root,rel)),`falta ${rel}`);
assert.ok(read('build/installer.nsh').includes('5.5.1'));assert.ok(read('README.md').includes('5.5.1'));assert.ok(read('CHANGELOG.md').includes('5.5.1'));
console.log(JSON.stringify({ok:true,version:pkg.version,files:all.length,navigationCases:cases.length+2},null,2));
