const fs=require('fs');const path=require('path');
const root=path.resolve(__dirname,'..');const must=(p)=>{if(!fs.existsSync(path.join(root,p)))throw new Error('Falta '+p)};
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const pkg=JSON.parse(read('package.json'));
if(pkg.version!=='5.3.0')throw new Error('Versión inesperada');
for(const f of ['shell/index.html','shell/nova53.js','shell/quantum53.css','shell/newtab.html','assets/reborn/quantum53-overview.png','assets/reborn/quantum53-store-poster.png','assets/reborn/whatsnew-renderer.png','assets/reborn/whatsnew-performance.png','assets/reborn/whatsnew-onboarding.png','assets/reborn/store-extensions.png','assets/logo/nova-quantum-reborn.svg','build/installer.nsh'])must(f);
const idx=read('shell/index.html');
for(const token of ['quantum53.css','nova53.js'])if(!idx.includes(token))throw new Error('index.html no carga '+token);
const js=read('shell/nova53.js');
for(const token of ['extensioncenter53','whatsnew53','guide53','Extension Center','NOVA 5.3','nova53'])if(!js.includes(token))throw new Error('Falta integración '+token);
if(js.includes("location.href='nova://whatsnew53'"))throw new Error('Ruta custom protocol no debe ejecutarse desde New Tab');
if(read('build/installer.nsh').includes('5.2.0'))throw new Error('Installer contiene 5.2.0');
if(fs.existsSync(path.join(root,'shell','themes.css')))throw new Error('themes.css heredado presente');
if(fs.existsSync(path.join(root,'assets','logos')))throw new Error('assets/logos heredado presente');
const notes=fs.readdirSync(root).filter(x=>/^RELEASE_NOTES_.*\.md$/i.test(x));if(notes.length!==1||notes[0]!=='RELEASE_NOTES_5.3.0.md')throw new Error('Notas raíz incorrectas');
console.log('Nova 5.3.0 QA PASSED');
console.log('Renderer visual aislado');
console.log('Extension Center registrado');
console.log('Whats New animado y primera ejecución protegida');
console.log('Recursos visuales presentes');
